import{a as f,S as h,i as m}from"./assets/vendor-b11e2a50.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();async function g(o,t){new URLSearchParams({key:"44040015-64d065a912d04f3627622b428",q:o,image_type:"photo",orientation:"horizontal",safesearch:"true"});try{const s="https://pixabay.com/api/",i=new URLSearchParams({key:"44040015-64d065a912d04f3627622b428",q:"car",image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:t}),e=`${s}?${i}`,r=await f.get(e);return console.log(r.data),r.data}catch{iziToast.error({position:"topRight",message:"Error"})}}function u(o){return o.map(t=>`<li class="gallery-list"><div class="gallery"><a href="${t.largeImageURL}"><img src="${t.webformatURL}" alt="${t.tags}" width="360px" height="100px"></a>
      <ul class="img-cont-list">
      <li class="img-cont-item">Likes<p class="img-cont-descr">${t.likes}</p></li>
      <li class="img-cont-item">Views<p class="img-cont-descr">${t.views}</p></li>
      <li class="img-cont-item">Comments<p class="img-cont-descr">${t.comments}</p></li>
      <li class="img-cont-item">Downloads<p class="img-cont-descr">${t.downloads}</p></li>
      </ul>
      </div>
      </li>`).join("")}function y(){new h(".gallery a",{navText:["&#5176;","&#5171;"],captionsData:"alt",captionDelay:250}).refresh()}const p=document.querySelector(".btn"),d=document.querySelector(".find-form"),a=document.querySelector(".galleriesBox");document.querySelector(".loader");let n=1,c="";d.addEventListener("submit",o=>{o.preventDefault(),a.innerHTML="",c=new FormData(d).get("find-text"),c!==""&&(a.innerHTML='<div class="loader"></div>',g(c,n).then(s=>{if(s.hits.length===0){m.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}),a.innerHTML="";return}const i=u(s.hits);a.innerHTML=i,y()}).catch(s=>m.error({position:"topRight",message:"Error"})).finally(()=>{o.target.reset()}))});p.addEventListener("click",async()=>{try{const o=await g(c,n),t=u(data.hits);a.innerHTML=t,n+=1,n>1&&(p.textContent="Fetch more posts")}catch(o){console.log(o)}});
//# sourceMappingURL=commonHelpers.js.map
